packages:
  - apps/*
  - packages/*

allowBuilds:
  electron: true
  esbuild: true
  electron-winstaller: false
  protobufjs: true

patchedDependencies:
  '@larksuiteoapi/node-sdk@1.73.0': patches/@larksuiteoapi__node-sdk@1.73.0.patch
