// Bilingual, practical guides for the Rovai website.
// Keep release-specific claims aligned with the published desktop packages.
(() => {
  const steps = (en, zh, enItems, zhItems, image) => ({
    title: [en, zh], steps: [enItems, zhItems], image
  });
  const note = (_en, _zh, enBody, zhBody) => ({
    kind: 'aside', body: [enBody, zhBody]
  });
  const guide = (en, zh, enLead, zhLead, enItems, zhItems, enCheck, zhCheck, image, extra) => ({
    title: [en, zh], lead: [enLead, zhLead],
    sections: [
      steps('How to use it', '操作步骤', enItems, zhItems, image),
      note('Check the result', '核对结果', enCheck, zhCheck),
      ...(extra ? [extra] : [])
    ]
  });

  const groups = [
    { en: 'Get started', zh: '开始使用', ids: ['installation', 'quickstart', 'tour'] },
    { en: 'Teammates and collaboration', zh: '队员与协作', ids: [
      'members', 'agents', 'conversations', 'messages', 'execution', 'tasks',
      'session-members', 'singlechat', 'approvals', 'files', 'recovery', 'message-queue'
    ] },
    { en: 'Plan and continue', zh: '计划与积累', ids: ['automations', 'missions', 'memory'] },
    { en: 'Connect and extend', zh: '连接与扩展', ids: ['skills', 'mcp', 'channels', 'remote'] },
    { en: 'Settings', zh: '设置', ids: ['compatibility', 'preferences', 'notifications', 'usage'] }
  ];

  const topics = {
    installation: guide('Download and install', '下载与安装',
      'Choose the package for your processor and install Rovai before setting up an Agent.',
      '先按系统与处理器选择安装包，安装后再配置智能体。',
      ['Open Download and choose the asset for macOS Apple Silicon, macOS Intel, or Windows x64.',
       'On macOS, open the DMG and drag Rovai AI into Applications. On Windows, run the per-user installer.',
       'Launch the installed App. Follow the release notes if your system shows a signing or publisher prompt.'],
      ['打开下载页，选择 macOS Apple 芯片、macOS Intel 或 Windows x64 对应文件。',
       'macOS 打开 DMG，把 Rovai AI 拖入“应用程序”；Windows 运行当前用户安装程序。',
       '从安装位置启动应用。若系统出现签名或发布者提示，请查看该版本的发布说明。'],
      'Confirm that the App opens, then go to Settings → Agents. An Agent requires its own installation and sign-in.',
      '确认应用能打开，再进入“设置 → 智能体”。编程智能体仍需按各自产品的方式安装和登录。'),

    quickstart: guide('Your first task', '快速开始',
      'Complete one small task with one teammate, then inspect what happened.',
      '用一位队员完成一个容易核对的小任务，并查看执行记录。',
      ['In Settings → Agents, check the coding Agent you plan to use. Finish its own sign-in if prompted.',
       'Open Teammates, select one teammate, choose that Agent and a model, then save the run configuration.',
       'Create a conversation for the intended project folder. Ask the teammate to read the project and explain its structure.',
       'Open the execution panel and compare the answer with the project files before assigning an edit.'],
      ['到“设置 → 智能体”检查准备使用的产品；若提示认证，先完成该产品自身的登录。',
       '打开“队员”，选择一位队员，设置智能体和模型并保存运行配置。',
       '为目标项目目录新建会话，让队员先阅读项目并解释目录结构。',
       '打开执行台，对照项目文件核对回答，再决定是否交给队员修改。'],
      'The first reply and its execution record should appear in the same conversation. If the Agent is unavailable, return to its status in Settings before retrying.',
      '首次回复及其执行记录应在同一会话中出现。若智能体不可用，先回“设置”检查状态，再决定是否重试。',
      'workspace-en.png'),

    tour: guide('Find your way around', '界面导览',
      'Use the main navigation to find the conversation, teammate, and long-running work you need.',
      '从主要入口快速找到会话、队员与持续工作。',
      ['Use the left side to create a conversation or reopen a recent project and conversation.',
       'Open Teammates to edit identities and run configuration; open Memory, Mission board, or Scheduled tasks for ongoing work.',
       'Inside a conversation, read messages in the center and open the current conversation details, execution panel, task view, or file preview when needed.',
       'Open Settings for Agents, connections, notifications, and general preferences.'],
      ['从左侧新建会话，或重新打开最近的项目与会话。',
       '进入“队员”编辑身份和运行配置；长期事项可从“记忆”“使命板”“定时任务”进入。',
       '在会话中阅读消息，需要时打开当前会话详情、执行台、任务视图或文件预览。',
       '进入“设置”配置智能体、连接、通知与通用偏好。'],
      'You can return to the same conversation to continue work; use the execution panel for run details rather than judging progress from messages alone.',
      '重新进入同一会话即可继续工作；执行细节请看执行台，不必只凭消息判断进度。',
      'workspace-en.png'),

    members: guide('Manage teammates', '队员管理',
      'Give each teammate a lasting identity and a clear role.',
      '为队员设置长期使用的身份与职责。',
      ['Open Teammates from the sidebar and select a person from the roster, or create a new teammate.',
       'Edit the name, team role, responsibilities, portrait, and working principles as needed. A new teammate can start with a name only.',
       'Choose Save teammate info. Run configuration has its own Save action lower on the same page.'],
      ['从侧栏打开“队员”，在名册中选择一位队员，或创建新队员。',
       '按需要填写名字、团队角色、专业职责、形象与工作准则；新队员只填名字也可以创建。',
       '点击“保存队员信息”。同页下方的运行配置需要单独保存。'],
      'Switch back to the roster and confirm the saved identity. If you changed the Agent or model too, check that “Save run configuration” completed separately.',
      '回到名册确认身份信息已保存。若还改了智能体或模型，也要单独确认“保存运行配置”已完成。',
      'members-en.png'),

    agents: guide('Agents and models', '智能体与模型配置',
      'Connect a coding Agent already installed on this computer and choose how a teammate uses it.',
      '接入这台电脑已安装的编程智能体，并决定队员如何使用它。',
      ['Install and sign in to the coding Agent using its own instructions, then open Settings → Agents to check its availability.',
       'Open Teammates, select a teammate, and scroll to their run configuration.',
       'Choose an Agent and model. “Default” follows the Agent’s own model choice; review any permission or filesystem options that Agent exposes.',
       'Save run configuration before returning to a conversation.'],
      ['先按产品自身的说明安装并登录编程智能体，再到“设置 → 智能体”检查可用状态。',
       '打开“队员”，选择队员，滚动到运行配置。',
       '选择智能体和模型；“默认”跟随智能体自己的模型选择。再核对该智能体提供的权限与文件系统选项。',
       '保存运行配置后再回到会话。'],
      'Confirm the teammate shows the selected Agent. A detected installation does not by itself prove that authentication, model access, or every permission is ready.',
      '确认队员显示所选智能体。检测到安装，不等于认证、模型访问及每项权限都已就绪。',
      'agents-en.png'),

    conversations: guide('Projects and conversations', '项目与会话',
      'Keep discussion and execution together in the project directory where work happens.',
      '把讨论和执行放在对应项目目录的会话中。',
      ['Choose New conversation in the sidebar, then select or create the project for the directory you intend to use.',
       'Name the conversation so you can find it later, and choose at least one teammate to participate.',
       'Open the conversation from the project or recent list when you want to continue the same work.'],
      ['在侧栏选择“新对话”，为准备处理的目录选择或创建项目。',
       '给会话取一个方便查找的名字，并加入至少一位队员。',
       '以后从项目或最近列表重新打开这段会话，继续原来的工作。'],
      'Check the project directory before asking an Agent to edit files. Messages, tasks, and execution records belong to the selected conversation.',
      '让智能体修改文件前，先核对项目目录。消息、任务与执行记录都归属当前所选会话。',
      'workspace-en.png'),

    messages: guide('Messages, mentions, and attachments', '消息、@ 提及与附件',
      'Give the right teammate a clear request and the files it needs.',
      '把任务和所需材料交给合适的队员。',
      ['Write the goal and expected result in the composer. Without a selected recipient, the conversation lead receives the message.',
       'Type @ and choose a teammate or all teammates from the picker when you want to route work explicitly.',
       'Use the attachment control, paste, or drag files and folders into the composer. Wait until attachments are ready, check the list, then send.'],
      ['在输入区写明目标和预期结果；未指定接收者时，由会话队长接收。',
       '需要明确分工时输入 @，从候选中选择一位队员或所有队员。',
       '通过附件按钮、粘贴或拖放加入文件与文件夹。等待附件准备完成，核对列表后再发送。'],
      'After sending, check the message’s recipient and attachment cards. Attached local files are references: if the originals move or become unreadable, a later read can fail.',
      '发送后核对消息接收者和附件卡片。本地附件引用原位置；原文件移动或失去读取权限后，后续读取可能失败。'),

    execution: guide('Follow execution', '查看执行',
      'Use the execution panel to see which teammate is working and what its Agent reported.',
      '用执行台查看谁正在处理任务，以及智能体报告了什么。',
      ['Open a conversation and expand its execution panel; choose the teammate or run you want to inspect.',
       'Read the run status, steps, commands, and tool results. Expand a step when you need its details.',
       'Use the original message link on a queued item to return to the request that caused it.'],
      ['打开会话并展开执行台，选择要查看的队员或执行。',
       '阅读运行状态、步骤、命令和工具结果；需要详情时展开相应步骤。',
       '遇到排队项，可用“定位原消息”回到触发它的请求。'],
      'A completed tool step is not the same as a completed run. Check the run’s final state, teammate reply, and relevant files together.',
      '单个工具步骤完成，不代表整次执行已完成。请结合运行终态、队员回复和相关文件核对。',
      'workspace-en.png'),

    tasks: guide('Tasks and responsibility', '任务与责任',
      'Track a specific piece of work and its owner inside a conversation.',
      '在会话里跟进一项具体工作及其负责人。',
      ['Open the conversation’s Task view to see current tasks and who owns them.',
       'Create a task with an outcome that can be checked, assign a teammate, and keep its scope smaller than a long-term mission.',
       'Open the task card or detail to review its current state and related execution.'],
      ['打开会话的“任务”视图，查看现有任务与负责人。',
       '创建任务时写清可核对的结果，指定队员，让范围小于长期使命。',
       '打开任务卡片或详情，查看当前状态及关联执行。'],
      'If you cancel a task, separately inspect any Agent run already in progress. Task cancellation does not automatically cancel that run.',
      '取消任务后仍要单独检查已开始的智能体执行；取消任务不会自动取消那次执行。'),

    'session-members': guide('Manage teammates in a conversation', '会话内队员管理',
      'Invite only the people needed for this conversation and adjust responsibility when work changes.',
      '按当前工作需要邀请队员，并在分工变化时调整责任。',
      ['Open the current conversation details and its teammate list. Use Invite to search and select people to add.',
       'Open a teammate’s row menu to inspect model information, set the lead, or remove the person from this conversation.',
       'Before removal, read the confirmation preview: it lists running work, tasks, or queued deliveries that may be affected.'],
      ['打开当前会话详情和队员列表，点击“邀请”，搜索并选择要加入的人。',
       '打开队员行尾菜单，查看模型信息、设置队长，或将其移出当前会话。',
       '移出前阅读确认预览，核对可能受影响的执行、任务或排队工作。'],
      'A conversation must retain a teammate. If removing its lead, select a successor first. After confirmation, wait for the affected work to settle before assigning more.',
      '会话必须保留至少一位队员；移出队长前需要先选继任者。确认后，等受影响的工作收口，再继续分配。'),

    singlechat: guide('One-on-one chat', '单聊',
      'Ask one teammate a focused question without putting its text on the public conversation.',
      '与一位队员单独讨论，正文不会进入会话公屏。',
      ['In the current conversation details, open One-on-one chat and choose a teammate.',
       'Write the question or attach a file, then send. You can switch to another teammate from the same panel.',
       'If you end the chat, read the confirmation carefully; the visible transcript is removed and a later chat starts blank.'],
      ['在当前会话详情中打开“单聊”，选择一位队员。',
       '输入问题或附上文件后发送。可在同一面板切换到另一位队员。',
       '要结束时先读确认提示；可见对话会移除，之后再找同一队员会从空白对话开始。'],
      'The panel says that one-on-one text does not enter the public conversation. Bring a conclusion back into the public conversation yourself if the whole team should use it.',
      '单聊面板会提示正文不进入公屏。若结论需要全队使用，请自行把结论带回公共会话。'),

    approvals: guide('Review approvals', '权限审批',
      'Decide on an Agent request after reading the exact action and its scope.',
      '看清智能体请求的操作和范围，再作决定。',
      ['When an Agent needs approval, open the pending approval area above the conversation composer or use the header’s pending indicator.',
       'Read the requested command or action and its supplied context. If several requests are waiting, move between them with the previous and next controls.',
       'Choose one of the options shown by that Agent. Decline or ask for clarification when the action does not match your intent.'],
      ['智能体请求审批时，打开输入区上方的待审批区域，或用会话顶部的待审批入口定位。',
       '阅读请求的命令或操作与上下文；有多项时用上一项、下一项逐个查看。',
       '选择该智能体提供的原生选项。操作不符合预期时拒绝，或先补充说明。'],
      'Return to the execution panel after deciding. An approval is a decision on this request, not proof that the requested action later succeeded.',
      '作出决定后回到执行台核对结果。审批只是针对这项请求作出决定，不代表操作随后一定成功。'),

    files: guide('Preview files and changes', '文件预览与累计变更',
      'Open relevant files beside the conversation and inspect changes supported by actual evidence.',
      '在会话旁预览文件，并核对有证据支持的变更。',
      ['Click an available file link in a message or execution step to open its preview beside the conversation.',
       'Open Files Changed to inspect the accumulated diff when the project and run provide reliable change evidence.',
       'Expand a changed file to read its diff; compare it with the teammate’s summary before accepting the result.'],
      ['点击消息或执行步骤中的可用文件链接，在会话旁打开预览。',
       '当项目与执行提供可靠变更证据时，打开“文件变更”查看累计差异。',
       '展开变更文件阅读差异，对照队员的总结再判断结果。'],
      'A file read belongs to execution history and does not count as a changed file. If there is no reliable diff, do not infer a modification from a tool label alone.',
      '读取文件属于执行记录，不算文件变更。没有可靠差异时，不要仅凭工具名称推断文件已修改。'),

    recovery: guide('Stop, interrupt, and resume', '停止、中断与恢复',
      'Stop the exact run you are looking at, then check what happened before continuing.',
      '停止当前关注的执行，并核对已发生的操作。',
      ['Open the execution panel, focus the active run, and use its Stop control when you want that run to stop.',
       'Wait for the recorded final state. Inspect the conversation and project files for changes made before the stop took effect.',
       'After an App, Agent, or network interruption, reopen the same conversation and inspect its run state before sending another request.'],
      ['打开执行台，定位到正在运行的那次执行，使用它的“停止”。',
       '等待界面显示实际终态，再检查会话和项目文件，确认停止生效前做过什么。',
       '应用、智能体或网络中断后，重新打开原会话，先核对运行状态，再决定是否发送新请求。'],
      'Stop only targets the focused Agent run. It does not erase completed file changes or automatically stop every queued item. Verify uncertain effects before retrying.',
      '“停止”只作用于当前聚焦的智能体执行，不会抹掉已完成的文件修改，也不会自动停止全部排队项。重试前先核对不确定的影响。'),

    'message-queue': guide('Withdraw and queue messages', '消息撤回与排队',
      'Understand when a sent message can be withdrawn and how later work waits its turn.',
      '了解消息何时还能撤回，以及后续工作如何排队。',
      ['Find your sent message. Its Withdraw action appears only while none of its recipients has claimed it; confirm to withdraw before that point.',
       'Open the execution panel to view waiting delivery or queued run cards and use Locate original message to check the request.',
       'In a one-on-one chat, a message sent while the teammate is busy joins that chat’s queue; edit it by moving it back to the composer or remove it from the queue.'],
      ['找到自己发送的消息。只有所有接收队员都尚未领取时才会显示“撤回”；此时可确认撤回。',
       '打开执行台查看等待投递或排队执行的卡片，用“定位原消息”核对请求。',
       '在单聊中，队员忙碌时发送的后续消息会进入该单聊队列；可移回输入区编辑，或从队列删除。'],
      'After the first recipient claims a public message, withdrawal is unavailable. The execution panel shows queued work but does not provide a message-withdraw action.',
      '公共消息被第一位接收队员领取后，就不能再撤回。执行台会显示排队工作，但不提供消息撤回操作。'),

    automations: guide('Scheduled tasks', '定时任务',
      'Have one teammate run a repeatable request on a schedule.',
      '让一位队员按计划处理可重复的工作。',
      ['Open Scheduled tasks, choose New or a template, then write the request in Prompt.',
       'Choose the teammate, project, and schedule: daily, weekdays, weekly, once, custom Cron, or manual.',
       'Save the task. Open its detail later to inspect the next run, enable state, and execution history.'],
      ['打开“定时任务”，点击“新建”或选用模板，并在 Prompt 中写明要做的工作。',
       '选择队员、项目与运行计划：每天、工作日、每周、仅一次、自定义 Cron 或手动触发。',
       '保存后，回到详情查看下次运行、启用状态与执行历史。'],
      'A scheduled run needs the host and Agent available at trigger time. Open a history row with a conversation to inspect what actually ran; skipped items may have no conversation.',
      '到达触发时间时，主机和智能体需要可用。打开有会话的历史记录核对实际执行；跳过的记录可能没有会话。',
      'automations-en.png'),

    missions: guide('Use the mission board', '使命板',
      'Track a larger goal on the board and open its working conversation when needed.',
      '用使命板跟进较大的目标，需要时打开对应的工作会话。',
      ['Open Mission board and choose New mission. Write a specific goal and description; add a project, teammates, lead, and source files where useful.',
       'Choose Create to save it, or Start mission when you want work to begin immediately.',
       'Open a card to see its conversation and activity. Use board filters or the card menu to find, edit, or change its status.'],
      ['打开“使命板”并点击“新使命”。写清目标与说明，按需要选择项目、队员、队长及来源文件。',
       '选择“新建”保存；要立即开始工作时选择“开始使命”。',
       '打开卡片查看相关会话与活动；通过筛选和卡片菜单查找、编辑或更新状态。'],
      'Check the team’s answer and available execution evidence before moving a mission to a completed state.',
      '把使命标记为完成前，先核对队员回复以及可用的执行证据。',
      'missions-en.png'),

    memory: guide('Review and manage memory', '协作记忆',
      'Keep useful decisions and lessons available beyond one conversation.',
      '让重要决定和经验在一段会话之后仍可查阅。',
      ['Open Memory from the sidebar. Choose Add memory for a decision or lesson that should still matter later.',
       'Select its scope and type, write a self-contained body, add up to three retrieval keys if useful, and save.',
       'Open a saved entry to review its source and versions. Use Revise to correct it, or Stop using when it no longer applies.'],
      ['从侧栏打开“记忆”。有需要长期保留的决定或经验时，点击“新增记忆”。',
       '选择范围与类型，写出脱离原会话也能理解的正文，按需填写最多三个检索关键词，然后保存。',
       '打开已保存条目查看来源和版本；内容有误可“修订”，不再适用时可“停止沿用”。'],
      'When starting related work, inspect the relevant memory and check it against the current project. A memory is context, not proof that a new task is complete.',
      '开始相关工作时，先查看有关记忆，并与当前项目现状对照。记忆提供背景，不能证明新任务已经完成。'),

    skills: guide('Use Skills', 'Skills',
      'Give teammates reusable instructions, or select an available Skill for one request.',
      '为队员配置可复用的做事方法，也可在单次请求中选择 Skill。',
      ['Open Settings → Skills, choose an Agent, and read the native Skills it exposes. This page is for inspection.',
       'Open Settings → Toolbox to read a built-in tool’s instructions and select the teammates who should receive it.',
       'For a single request, type / in the conversation composer and choose an available Skill from the picker before sending.'],
      ['打开“设置 → Skills”，选择智能体并阅读它提供的原生 Skill；此页用于查看。',
       '到“设置 → 工具箱”阅读内置工具的说明，再选择要使用它的队员。',
       '单次请求可在会话输入区输入 /，从候选中选择可用 Skill，再发送消息。'],
      'The selected Skill appears as a structured token in the draft. Check the run and result to see how the Agent used it; a visible Skill does not guarantee the Agent followed every instruction.',
      '选中的 Skill 会以结构化标记出现在草稿中。查看执行和结果，核对智能体如何使用它；标记可见不代表智能体遵循了每条指令。'),

    mcp: guide('Connect MCP tools', 'MCP',
      'Make an external tool available where the chosen Agent can use it.',
      '把外部工具接到需要它的智能体工作中。',
      ['Open Settings → MCP and choose Add configuration or Import from this computer.',
       'For a new server, edit its JSON configuration, check the command or endpoint and required credentials, then select the teammates who may use it and save.',
       'Use a small read-only lookup in a conversation to verify the Agent can actually use the tool.'],
      ['打开“设置 → MCP”，选择“添加配置”或“从本机导入”。',
       '新建服务时编辑 JSON 配置，核对命令或地址及所需凭证，选择允许使用的队员后保存。',
       '先在会话里做一个小范围读取或查询，验证智能体确实能用到工具。'],
      'If the check fails, revisit the server configuration, credentials, and selected Agent. A configured server is not by itself evidence of a successful tool call.',
      '验证失败时，检查服务配置、认证信息与所选智能体。服务已配置，不等于工具调用已经成功。'),

    channels: guide('Connect a channel', '渠道接入',
      'Reach a teammate through Feishu, Lark, or DingTalk while work runs on the connected host.',
      '通过飞书、Lark 或钉钉联系队员，执行仍在连接的主机上进行。',
      ['Open Settings → Channels and choose the provider that matches your organization.',
       'Follow that provider’s account, app, and bot setup shown in Rovai. Configure a teammate bot and finish the provider’s publication step.',
       'Check that the bot is published and connected, then send a small test message in the intended external chat.'],
      ['打开“设置 → 渠道”，选择组织实际使用的飞书、Lark 或钉钉。',
       '按页面指引完成对应平台的账号、应用和 Bot 设置，为队员配置 Bot 并完成平台发布步骤。',
       '确认 Bot 已发布且已连接，再从准备使用的外部会话发送一条简短测试消息。'],
      'Verify the reply and linked execution record before assigning larger work. Provider permissions and publication requirements differ.',
      '确认回复与关联执行记录后再交付更大的任务；各平台的权限与发布要求不同。',
      'channels-en.png'),

    remote: guide('Browser and remote access', '浏览器与远程访问',
      'Open the same workspace in a browser while the App and Agent continue on the host.',
      '从浏览器访问同一工作台，应用和智能体仍在主机上运行。',
      ['On the host, open Settings → Remote connection and enable the service.',
       'Use the address shown there on another browser. Complete the sign-in step before opening a conversation.',
       'Keep the host and Rovai running. For another network, first arrange a private network or HTTPS entry that can reach the host.'],
      ['在主机上打开“设置 → 远程连接”并启用服务。',
       '在另一台设备的浏览器打开页面给出的地址，完成登录后进入会话。',
       '保持主机与 Rovai 运行。跨网络访问前，先配置能到达主机的私有网络或 HTTPS 入口。'],
      'Try opening an existing conversation and reading a reply. Project files and Agent execution remain on the host; a browser connection does not move them.',
      '尝试打开已有会话并查看回复。项目文件和智能体执行仍在主机上，浏览器连接不会把它们迁到访问设备。',
      'remote-en.png'),

    compatibility: guide('Platforms and Agents', '支持平台与智能体',
      'Check the package and Agent that are actually available on your computer.',
      '以目标电脑上真实可用的安装包与智能体为准。',
      ['On Download, choose macOS Apple Silicon, macOS Intel, or Windows x64 according to your computer and the current release assets.',
       'Install the coding Agent you want to use and complete its own sign-in.',
       'In Settings → Agents, check its status on this computer; then inspect available models and permissions in a teammate’s run configuration.'],
      ['在下载页按电脑选择 macOS Apple 芯片、macOS Intel 或 Windows x64，并核对当前版本实际提供的文件。',
       '安装要用的编程智能体，并完成该产品自己的登录。',
       '到“设置 → 智能体”检查这台电脑上的状态，再到队员运行配置核对模型与权限选项。'],
      'Availability can vary by platform, Agent version, and account. If the App finds an installation but the Agent cannot run, resolve its reported status before trying a task.',
      '可用性会随平台、智能体版本和账号变化。如果应用检测到安装却不能运行，请先处理页面报告的状态，再尝试任务。',
      'agents-en.png'),

    preferences: guide('General settings', '通用设置',
      'Set the App’s language, startup destination, conversation behavior, and appearance.',
      '调整界面语言、启动位置、会话方式和外观。',
      ['Open Settings → General to choose the interface language, startup location, and new-conversation preferences.',
       'If enabling one-click conversation creation, check the default teammates and lead first.',
       'Open Appearance for the available display options; return to an existing conversation to see the result.'],
      ['打开“设置 → 通用”，选择界面语言、启动位置与新会话偏好。',
       '若开启一键创建会话，先核对默认队员和队长。',
       '到“外观”调整可用显示选项，再回到已有会话检查效果。'],
      'Changing language or appearance changes presentation; it does not rewrite previously sent message content.',
      '语言和外观只改变显示方式，不会改写已经发送的消息正文。'),

    notifications: guide('Notification settings', '通知设置',
      'Choose which events should draw your attention.',
      '选择哪些事件需要提醒你。',
      ['Open Settings → Notifications and review the controls available on your platform.',
       'Keep reminders you need for approvals, mentions, or work results; turn off categories you do not need.',
       'When a notification arrives, open it to return to the relevant conversation or request.'],
      ['打开“设置 → 通知”，查看当前平台提供的控制项。',
       '保留审批、提及或工作结果等需要你处理的提醒，关闭不需要的类别。',
       '收到通知后打开它，回到关联会话或请求。'],
      'Read the source message or approval before acting. A notification summary may leave out the details needed for a decision.',
      '采取操作前先读原消息或审批请求。通知摘要可能省略作出决定所需的细节。'),

    usage: guide('Usage and monitoring', '用量与运行监控',
      'Inspect what the Agent reported for runs and usage, with its coverage in mind.',
      '查看智能体实际报告的运行与用量，并留意数据覆盖范围。',
      ['Open Settings → Agent usage, then select the available Agent and time range.',
       'Review the reported tokens, cache, and attributable cost together with the run records.',
       'If a value is missing, inspect the source Agent or the run before drawing a comparison.'],
      ['打开“设置 → 智能体用量”，选择页面提供的智能体与时间范围。',
       '结合执行记录查看实际报告的 Token、Cache 与可归因成本。',
       '若某项缺失，先检查来源智能体或执行记录，再比较数据。'],
      'Missing data means unknown, not zero. A cost shown here may differ from the provider’s final bill.',
      '缺失数据表示未知，不等于零。这里显示的成本也可能与服务商最终账单不同。')
  };

  window.RovaiDocs = { groups, topics };
})();
