use serde::{Deserialize, Serialize};

/// Public Web operations are admitted individually. This enum must not be
/// generated by copying every internal Core RPC; paths, credentials, recovery
/// and the legacy shared draft remain outside the network capability.
#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
pub enum Operation {
    #[serde(rename = "app.info")]
    AppInfo,
    #[serde(rename = "members.list")]
    Members,
    #[serde(rename = "members.get")]
    Member,
    #[serde(rename = "navigation.snapshot")]
    Navigation,
    #[serde(rename = "navigation.groupCamps")]
    GroupCamps,
    #[serde(rename = "camps.exists")]
    CampExists,
    #[serde(rename = "camp.messages.page")]
    Messages,
    #[serde(rename = "camp.messages.around")]
    MessagesAround,
    #[serde(rename = "camp.messages.find")]
    FindMessages,
    #[serde(rename = "tasks.list")]
    Tasks,
    #[serde(rename = "tasks.get")]
    Task,
    #[serde(rename = "memory.list")]
    Memories,
    #[serde(rename = "memory.get")]
    Memory,
    #[serde(rename = "automations.list")]
    Automations,
    #[serde(rename = "automations.get")]
    Automation,
    #[serde(rename = "automations.runs.list")]
    AutomationRuns,
    #[serde(rename = "runtime.installations.list")]
    Installations,
    #[serde(rename = "runtime.subsystems.get")]
    Subsystems,
    #[serde(rename = "monitoring.snapshot")]
    Monitoring,
    #[serde(rename = "skills.list")]
    Skills,
    #[serde(rename = "skills.get")]
    Skill,
    #[serde(rename = "mcp.config.get")]
    Mcp,
}

impl Operation {
    pub fn project(self, mut value: serde_json::Value) -> serde_json::Value {
        use serde_json::json;
        match self {
            Self::AppInfo => json!({"name":value["name"],"version":value["version"]}),
            Self::Mcp => {
                json!({"servers":value["servers"].as_array().map(|servers| servers.iter().map(|server| json!({
                "serverId":server["serverId"], "name":server["name"], "transport":server["transport"],
                "enabled":server["enabled"], "assignedAgentIds":server["assignedAgentIds"]
            })).collect::<Vec<_>>()).unwrap_or_default()})
            }
            // Mutation affordances belong to each client capability, not to a
            // copied internal view. Never advertise desktop actions on the Web.
            _ => {
                remove_actions(&mut value);
                value
            }
        }
    }

    pub fn method(self) -> &'static str {
        match self {
            Self::AppInfo => "app.info",
            Self::Members => "members.list",
            Self::Member => "members.get",
            Self::Navigation => "navigation.snapshot",
            Self::GroupCamps => "navigation.groupCamps",
            Self::CampExists => "camps.exists",
            Self::Messages => "camp.messages.page",
            Self::MessagesAround => "camp.messages.around",
            Self::FindMessages => "camp.messages.find",
            Self::Tasks => "tasks.list",
            Self::Task => "tasks.get",
            Self::Memories => "memory.list",
            Self::Memory => "memory.get",
            Self::Automations => "automations.list",
            Self::Automation => "automations.get",
            Self::AutomationRuns => "automations.runs.list",
            Self::Installations => "runtime.installations.list",
            Self::Subsystems => "runtime.subsystems.get",
            Self::Monitoring => "monitoring.snapshot",
            Self::Skills => "skills.list",
            Self::Skill => "skills.get",
            Self::Mcp => "mcp.config.get",
        }
    }
}

fn remove_actions(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(object) => {
            if object.contains_key("availableActions") {
                object.insert("availableActions".into(), serde_json::json!([]));
            }
            for value in object.values_mut() {
                remove_actions(value);
            }
        }
        serde_json::Value::Array(array) => {
            for value in array {
                remove_actions(value);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::Operation;
    use serde_json::json;

    // Owns the network projection boundary, not Core's internal MCP model.
    #[test]
    fn public_projection_excludes_mcp_credentials_and_desktop_mutation_actions() {
        let projected = Operation::Mcp.project(json!({"servers":[{
            "serverId":"fixture", "name":"Example", "enabled":true,
            "transport":"http", "assignedAgentIds":[],
            "headers":{"Authorization":"fixture-secret"},
            "definitionJson":"fixture-secret", "endpoint":"https://fixture.invalid/?secret=fixture-secret",
            "futureCredentialField":"fixture-secret"
        }]}));
        assert_eq!(
            projected,
            json!({"servers":[{"serverId":"fixture", "name":"Example", "enabled":true,
            "transport":"http", "assignedAgentIds":[]}]})
        );
        assert_eq!(
            Operation::Tasks
                .project(json!({"items":[{"body":"keep content", "availableActions":["edit"]}]})),
            json!({"items":[{"body":"keep content", "availableActions":[]}]})
        );
        assert!(serde_json::from_value::<Operation>(json!("host.web.rotate")).is_err());
        assert!(
            serde_json::from_value::<Operation>(json!("camp.message.send_user_draft")).is_err()
        );
    }
}
