use serde::{Deserialize, Serialize};

/// Public Web operations are admitted individually. This enum must not be
/// generated by copying every internal Core RPC; credentials, recovery
/// and the legacy shared draft remain outside the network capability.
#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
pub enum Operation {
    #[serde(rename = "camps.open")]
    CampOpen,
    #[serde(rename = "camps.enter")]
    CampEnter,
    #[serde(rename = "navigation.campViewed")]
    CampViewed,
    #[serde(rename = "memory.hearthReviewItems.list")]
    MemoryReviews,
    #[serde(rename = "health.check")]
    Health,
    #[serde(rename = "skills.deliveryGroups.list")]
    SkillGroups,
    #[serde(rename = "agentRunEvidence.list")]
    RunEvidence,
    #[serde(rename = "agentRunEvidence.getContent")]
    RunEvidenceContent,
    #[serde(rename = "app.info")]
    AppInfo,
    #[serde(rename = "members.list")]
    Members,
    #[serde(rename = "members.get")]
    Member,
    #[serde(rename = "navigation.snapshot")]
    Navigation,
    #[serde(rename = "navigation.groupCamps")]
    GroupCamps,
    #[serde(rename = "camps.exists")]
    CampExists,
    #[serde(rename = "camp.messages.page")]
    Messages,
    #[serde(rename = "camp.messages.around")]
    MessagesAround,
    #[serde(rename = "camp.messages.find")]
    FindMessages,
    #[serde(rename = "tasks.list")]
    Tasks,
    #[serde(rename = "tasks.get")]
    Task,
    #[serde(rename = "memory.list")]
    Memories,
    #[serde(rename = "memory.get")]
    Memory,
    #[serde(rename = "automations.list")]
    Automations,
    #[serde(rename = "automations.get")]
    Automation,
    #[serde(rename = "automations.runs.list")]
    AutomationRuns,
    #[serde(rename = "runtime.installations.list")]
    Installations,
    #[serde(rename = "runtime.subsystems.get")]
    Subsystems,
    #[serde(rename = "monitoring.snapshot")]
    Monitoring,
    #[serde(rename = "skills.list")]
    Skills,
    #[serde(rename = "skills.get")]
    Skill,
    #[serde(rename = "mcp.config.get")]
    Mcp,
    #[serde(rename = "camp.composerDraft.get")]
    DraftGet,
    #[serde(rename = "camp.composerDraft.save")]
    DraftSave,
    #[serde(rename = "camp.composerDraft.discard")]
    DraftDiscard,
    #[serde(rename = "camp.composerDraft.startReply")]
    DraftReply,
    #[serde(rename = "camp.composerDraft.cancelReply")]
    DraftCancelReply,
    #[serde(rename = "camp.composerDraft.resolveReplyRecipient")]
    DraftReplyRecipient,
    #[serde(rename = "camp.composerDraft.dismissContinuation")]
    DraftDismissContinuation,
    #[serde(rename = "camp.composerDraft.resolveContinuationRecipient")]
    DraftContinuationRecipient,
    #[serde(rename = "camp.composerDraft.removeAttachment")]
    DraftRemoveAttachment,
    #[serde(rename = "messageQuotes.mutateDraft")]
    DraftQuote,
    #[serde(rename = "camp.pendingInputs.get")]
    PendingInputs,
    #[serde(rename = "camp.pendingInputs.edit")]
    PendingEdit,
    #[serde(rename = "camp.messages.send")]
    Send,
    #[serde(rename = "action.approvals.resolve")]
    Approval,
    #[serde(rename = "agentRuns.cancel")]
    CancelRun,
    #[serde(rename = "campTurns.cancel")]
    CancelTurn,
    #[serde(rename = "commands.reconcile")]
    Reconcile,
    #[serde(rename = "camps.create")]
    CampCreate,
    #[serde(rename = "camps.creationPreflight")]
    CampCreationDefaults,
    #[serde(rename = "camps.members.add")]
    CampAddMember,
    #[serde(rename = "camps.members.remove")]
    CampRemoveMember,
    #[serde(rename = "camps.members.removalPreview")]
    CampRemovalPreview,
    #[serde(rename = "camps.changeDefaultLead")]
    CampLead,
    #[serde(rename = "members.create")]
    MemberCreate,
    #[serde(rename = "members.update")]
    MemberUpdate,
    #[serde(rename = "members.avatar.set")]
    MemberAvatar,
    #[serde(rename = "members.runtime.set")]
    MemberRuntime,
    #[serde(rename = "members.runtime.clear")]
    MemberClearRuntime,
    #[serde(rename = "workspaces.inspect")]
    WorkspaceInspect,
    #[serde(rename = "workspaces.validate")]
    WorkspaceValidate,
    #[serde(rename = "agentRunImages.read")]
    RunImages,
    #[serde(rename = "agentRunFileChanges.get")]
    RunFiles,
    #[serde(rename = "agentRuns.diagnostic.get")]
    RunDiagnostic,
    #[serde(rename = "runtime.product.ensure")]
    RuntimeEnsure,
    #[serde(rename = "runtime.product.check")]
    RuntimeCheck,
    #[serde(rename = "runtime.modelCatalog.open")]
    RuntimeCatalog,
    #[serde(rename = "runtime.discovery.rescan")]
    RuntimeDiscover,
}

impl Operation {
    pub fn timeout(self) -> std::time::Duration {
        std::time::Duration::from_secs(match self {
            Self::RuntimeCheck | Self::RuntimeCatalog | Self::RuntimeDiscover => 120,
            _ => 15,
        })
    }
    pub fn project(self, mut value: serde_json::Value) -> serde_json::Value {
        use serde_json::json;
        match self {
            Self::AppInfo => json!({"name":value["name"],"version":value["version"]}),
            Self::Mcp => {
                json!({"servers":value["servers"].as_array().map(|servers| servers.iter().map(|server| json!({
                "serverId":server["serverId"], "name":server["name"], "transport":server["transport"],
                "enabled":server["enabled"], "assignedAgentIds":server["assignedAgentIds"]
            })).collect::<Vec<_>>()).unwrap_or_default()})
            }
            // Mutation affordances belong to each client capability, not to a
            // copied internal view. Never advertise desktop actions on the Web.
            _ => {
                remove_actions(&mut value);
                value
            }
        }
    }

    pub fn method(self) -> &'static str {
        match self {
            Self::RuntimeEnsure => "runtime.product.ensure",
            Self::RuntimeCheck => "runtime.product.check",
            Self::RuntimeCatalog => "runtime.modelCatalog.open",
            Self::RuntimeDiscover => "runtime.discovery.rescan",
            Self::DraftGet => "camp.composerDraft.get",
            Self::DraftSave => "camp.composerDraft.save",
            Self::DraftDiscard => "camp.composerDraft.discard",
            Self::DraftReply => "camp.composerDraft.startReply",
            Self::DraftCancelReply => "camp.composerDraft.cancelReply",
            Self::DraftReplyRecipient => "camp.composerDraft.resolveReplyRecipient",
            Self::DraftDismissContinuation => "camp.composerDraft.dismissContinuation",
            Self::DraftContinuationRecipient => "camp.composerDraft.resolveContinuationRecipient",
            Self::DraftRemoveAttachment => "camp.composerDraft.removeAttachment",
            Self::DraftQuote => "messageQuotes.mutateDraft",
            Self::PendingInputs => "camp.pendingInputs.get",
            Self::PendingEdit => "camp.pendingInputs.edit",
            Self::Send => "camp.messages.send",
            Self::Approval => "action.approvals.resolve",
            Self::CancelRun => "agentRuns.cancel",
            Self::CancelTurn => "campTurns.cancel",
            Self::Reconcile => "commands.reconcile",
            Self::CampCreate => "camps.create",
            Self::CampCreationDefaults => "camps.creationPreflight",
            Self::CampAddMember => "camps.members.add",
            Self::CampRemoveMember => "camps.members.remove",
            Self::CampRemovalPreview => "camps.members.removalPreview",
            Self::CampLead => "camps.changeDefaultLead",
            Self::MemberCreate => "members.create",
            Self::MemberUpdate => "members.update",
            Self::MemberAvatar => "members.avatar.set",
            Self::MemberRuntime => "members.runtime.set",
            Self::MemberClearRuntime => "members.runtime.clear",
            Self::WorkspaceInspect => "workspaces.inspect",
            Self::WorkspaceValidate => "workspaces.validate",
            Self::RunImages => "agentRunImages.read",
            Self::RunFiles => "agentRunFileChanges.get",
            Self::RunDiagnostic => "agentRuns.diagnostic.get",
            Self::CampOpen => "camps.open",
            Self::CampEnter => "camps.enter",
            Self::CampViewed => "navigation.campViewed",
            Self::MemoryReviews => "memory.hearthReviewItems.list",
            Self::Health => "health.check",
            Self::SkillGroups => "skills.deliveryGroups.list",
            Self::RunEvidence => "agentRunEvidence.list",
            Self::RunEvidenceContent => "agentRunEvidence.getContent",
            Self::AppInfo => "app.info",
            Self::Members => "members.list",
            Self::Member => "members.get",
            Self::Navigation => "navigation.snapshot",
            Self::GroupCamps => "navigation.groupCamps",
            Self::CampExists => "camps.exists",
            Self::Messages => "camp.messages.page",
            Self::MessagesAround => "camp.messages.around",
            Self::FindMessages => "camp.messages.find",
            Self::Tasks => "tasks.list",
            Self::Task => "tasks.get",
            Self::Memories => "memory.list",
            Self::Memory => "memory.get",
            Self::Automations => "automations.list",
            Self::Automation => "automations.get",
            Self::AutomationRuns => "automations.runs.list",
            Self::Installations => "runtime.installations.list",
            Self::Subsystems => "runtime.subsystems.get",
            Self::Monitoring => "monitoring.snapshot",
            Self::Skills => "skills.list",
            Self::Skill => "skills.get",
            Self::Mcp => "mcp.config.get",
        }
    }
}

fn remove_actions(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(object) => {
            if object.contains_key("availableActions") {
                object.insert("availableActions".into(), serde_json::json!([]));
            }
            for value in object.values_mut() {
                remove_actions(value);
            }
        }
        serde_json::Value::Array(array) => {
            for value in array {
                remove_actions(value);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::Operation;
    use serde_json::json;

    // Owns the network projection boundary, not Core's internal MCP model.
    #[test]
    fn public_projection_excludes_mcp_credentials_and_desktop_mutation_actions() {
        let projected = Operation::Mcp.project(json!({"servers":[{
            "serverId":"fixture", "name":"Example", "enabled":true,
            "transport":"http", "assignedAgentIds":[],
            "headers":{"Authorization":"fixture-secret"},
            "definitionJson":"fixture-secret", "endpoint":"https://fixture.invalid/?secret=fixture-secret",
            "futureCredentialField":"fixture-secret"
        }]}));
        assert_eq!(
            projected,
            json!({"servers":[{"serverId":"fixture", "name":"Example", "enabled":true,
            "transport":"http", "assignedAgentIds":[]}]})
        );
        assert_eq!(
            Operation::Tasks
                .project(json!({"items":[{"body":"keep content", "availableActions":["edit"]}]})),
            json!({"items":[{"body":"keep content", "availableActions":[]}]})
        );
        assert!(serde_json::from_value::<Operation>(json!("host.web.rotate")).is_err());
        assert!(
            serde_json::from_value::<Operation>(json!("camp.message.send_user_draft")).is_err()
        );
    }
}
