use serde::{Deserialize, Serialize};

/// Public Web operations are admitted individually. This enum must not be
/// generated by copying every internal Core RPC; credentials, recovery
/// and the legacy shared draft remain outside the network capability.
#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
pub enum Operation {
    #[serde(rename = "missions.workspace.cleanup")]
    MissionWorkspaceCleanup,
    #[serde(rename = "missions.cleanup.list")]
    MissionCleanupList,
    #[serde(rename = "missions.cleanup.retry")]
    MissionCleanupRetry,
    #[serde(rename = "missions.list")]
    MissionList,
    #[serde(rename = "missions.get")]
    MissionGet,
    #[serde(rename = "missions.activity")]
    MissionActivity,
    #[serde(rename = "missions.delivery")]
    MissionDelivery,
    #[serde(rename = "missions.changes")]
    MissionChanges,
    #[serde(rename = "missions.fileDiff")]
    MissionFileDiff,
    #[serde(rename = "missions.diffSession.release")]
    MissionDiffSessionRelease,
    #[serde(rename = "missions.create")]
    MissionCreate,
    #[serde(rename = "missions.update")]
    MissionUpdate,
    #[serde(rename = "missions.status")]
    MissionStatus,
    #[serde(rename = "missions.start")]
    MissionStart,
    #[serde(rename = "missions.linkPr")]
    MissionLinkPr,

    #[serde(rename = "preferences.newConversation.get")]
    NewConversationGet,
    #[serde(rename = "preferences.newConversation.setDefaults")]
    NewConversationSetDefaults,
    #[serde(rename = "preferences.newConversation.setOneClick")]
    NewConversationSetOneClick,
    #[serde(rename = "preferences.newConversation.invalidate")]
    NewConversationInvalidate,

    #[serde(rename = "camps.rename")]
    CampRename,
    #[serde(rename = "camps.delete")]
    CampDelete,
    #[serde(rename = "camps.deletionIssues")]
    CampDeletionIssues,
    #[serde(rename = "camps.retryDeletion")]
    CampRetryDeletion,
    #[serde(rename = "camps.discardPending")]
    CampDiscardPending,
    #[serde(rename = "camps.members.fast.check")]
    CampFastCheck,
    #[serde(rename = "camps.members.fast.set")]
    CampFastSet,
    #[serde(rename = "members.removalPreview")]
    MemberRemovalPreview,
    #[serde(rename = "members.remove")]
    MemberRemove,
    #[serde(rename = "members.reorder")]
    MemberReorder,
    #[serde(rename = "runtime.subsystems.retry")]
    SubsystemRetry,
    #[serde(rename = "notifications.inbox")]
    NotificationInbox,
    #[serde(rename = "notifications.changesSince")]
    NotificationChanges,
    #[serde(rename = "notifications.preference.get")]
    NotificationPreference,
    #[serde(rename = "notifications.preference.update")]
    NotificationPreferenceUpdate,
    #[serde(rename = "notifications.acknowledge")]
    NotificationAcknowledge,
    #[serde(rename = "notifications.acknowledgeVisibleSources")]
    NotificationVisible,
    #[serde(rename = "diagnostics.check")]
    DiagnosticsCheck,
    #[serde(rename = "diagnostics.export")]
    DiagnosticsExport,
    #[serde(rename = "skills.reconcile")]
    SkillReconcile,

    #[serde(rename = "singleChat.list")]
    SingleChatList,
    #[serde(rename = "singleChat.get")]
    SingleChatGet,
    #[serde(rename = "singleChat.open")]
    SingleChatOpen,
    #[serde(rename = "singleChat.send")]
    SingleChatSend,
    #[serde(rename = "singleChat.end")]
    SingleChatEnd,
    #[serde(rename = "singleChat.pendingInputs.edit")]
    SingleChatPendingEdit,
    #[serde(rename = "singleChat.composerDraft.removeAttachment")]
    SingleChatRemoveAttachment,

    #[serde(rename = "skills.content.read")]
    SkillContent,
    #[serde(rename = "skills.import.inspect")]
    SkillImportInspect,
    #[serde(rename = "skills.import.github.inspect")]
    SkillGithubInspect,
    #[serde(rename = "skills.import.commit")]
    SkillImportCommit,
    #[serde(rename = "skills.setEnabled")]
    SkillEnable,
    #[serde(rename = "skills.setGroupAssignments")]
    SkillGroupsSet,
    #[serde(rename = "skills.delete")]
    SkillDelete,
    #[serde(rename = "mcp.servers.create")]
    McpCreate,
    #[serde(rename = "mcp.servers.update")]
    McpUpdate,
    #[serde(rename = "mcp.servers.setMembers")]
    McpMembers,
    #[serde(rename = "mcp.servers.setEnabled")]
    McpEnable,
    #[serde(rename = "mcp.servers.delete")]
    McpDelete,
    #[serde(rename = "mcp.servers.reveal")]
    McpReveal,
    #[serde(rename = "mcp.config.repairPermissions")]
    McpRepair,
    #[serde(rename = "mcp.import.scan")]
    McpScan,
    #[serde(rename = "mcp.import.commit")]
    McpImport,
    #[serde(rename = "runtime.startup.get")]
    RuntimeStartupGet,
    #[serde(rename = "runtime.startup.save")]
    RuntimeStartupSave,
    #[serde(rename = "runtime.startup.inspect")]
    RuntimeStartupInspect,
    #[serde(rename = "runtime.startup.check")]
    RuntimeStartupCheck,

    #[serde(rename = "navigation.findCamp")]
    NavigationFindCamp,
    #[serde(rename = "agentRunExecution.page")]
    RunExecutionPage,
    #[serde(rename = "agentRunExecution.changes")]
    RunExecutionChanges,
    #[serde(rename = "tasks.create")]
    TaskCreate,
    #[serde(rename = "tasks.update")]
    TaskUpdate,
    #[serde(rename = "memory.create")]
    MemoryCreate,
    #[serde(rename = "memory.revise")]
    MemoryRevise,
    #[serde(rename = "memory.retire")]
    MemoryRetire,
    #[serde(rename = "memory.reactivate")]
    MemoryReactivate,
    #[serde(rename = "memory.forget")]
    MemoryForget,
    #[serde(rename = "memory.supersede")]
    MemorySupersede,
    #[serde(rename = "memory.review.schedule")]
    MemorySchedule,
    #[serde(rename = "memory.hearthReviewItems.accept")]
    MemoryAccept,
    #[serde(rename = "memory.hearthReviewItems.reject")]
    MemoryReject,
    #[serde(rename = "memory.export")]
    MemoryExport,
    #[serde(rename = "automations.create")]
    AutomationCreate,
    #[serde(rename = "automations.update")]
    AutomationUpdate,
    #[serde(rename = "automations.close")]
    AutomationClose,
    #[serde(rename = "automations.delete")]
    AutomationDelete,
    #[serde(rename = "automations.run")]
    AutomationRun,

    #[serde(rename = "camps.open")]
    CampOpen,
    #[serde(rename = "camps.enter")]
    CampEnter,
    #[serde(rename = "navigation.campViewed")]
    CampViewed,
    #[serde(rename = "memory.hearthReviewItems.list")]
    MemoryReviews,
    #[serde(rename = "health.check")]
    Health,
    #[serde(rename = "skills.deliveryGroups.list")]
    SkillGroups,
    #[serde(rename = "agentRunEvidence.list")]
    RunEvidence,
    #[serde(rename = "agentRunEvidence.getContent")]
    RunEvidenceContent,
    #[serde(rename = "app.info")]
    AppInfo,
    #[serde(rename = "members.list")]
    Members,
    #[serde(rename = "members.get")]
    Member,
    #[serde(rename = "navigation.snapshot")]
    Navigation,
    #[serde(rename = "navigation.camps")]
    NavigationCamps,
    #[serde(rename = "navigation.groupCamps")]
    GroupCamps,
    #[serde(rename = "camps.exists")]
    CampExists,
    #[serde(rename = "camp.messages.page")]
    Messages,
    #[serde(rename = "camp.messages.around")]
    MessagesAround,
    #[serde(rename = "camp.messages.find")]
    FindMessages,
    #[serde(rename = "tasks.list")]
    Tasks,
    #[serde(rename = "tasks.get")]
    Task,
    #[serde(rename = "memory.list")]
    Memories,
    #[serde(rename = "memory.get")]
    Memory,
    #[serde(rename = "automations.list")]
    Automations,
    #[serde(rename = "automations.get")]
    Automation,
    #[serde(rename = "automations.runs.list")]
    AutomationRuns,
    #[serde(rename = "runtime.installations.list")]
    Installations,
    #[serde(rename = "runtime.subsystems.get")]
    Subsystems,
    #[serde(rename = "monitoring.snapshot")]
    Monitoring,
    #[serde(rename = "skills.list")]
    Skills,
    #[serde(rename = "skills.get")]
    Skill,
    #[serde(rename = "toolbox.list")]
    ToolboxList,
    #[serde(rename = "toolbox.read")]
    ToolboxRead,
    #[serde(rename = "toolbox.setMembers")]
    ToolboxSetMembers,
    #[serde(rename = "nativeSkills.list")]
    NativeSkillsList,
    #[serde(rename = "nativeSkills.read")]
    NativeSkillsRead,
    #[serde(rename = "skills.candidates")]
    SkillCandidates,
    #[serde(rename = "mcp.config.get")]
    Mcp,
    #[serde(rename = "messageQuotes.mutateDraft")]
    DraftQuote,
    #[serde(rename = "messageQuotes.capture")]
    CaptureQuote,
    #[serde(rename = "camp.messages.send")]
    Send,
    #[serde(rename = "camp.messages.withdraw")]
    WithdrawMessage,
    #[serde(rename = "action.approvals.resolve")]
    Approval,
    #[serde(rename = "agentRuns.cancel")]
    CancelRun,
    #[serde(rename = "commands.reconcile")]
    Reconcile,
    #[serde(rename = "camps.create")]
    CampCreate,
    #[serde(rename = "camps.creationPreflight")]
    CampCreationDefaults,
    #[serde(rename = "camps.members.add")]
    CampAddMember,
    #[serde(rename = "camps.members.remove")]
    CampRemoveMember,
    #[serde(rename = "camps.members.removalPreview")]
    CampRemovalPreview,
    #[serde(rename = "camps.changeDefaultLead")]
    CampLead,
    #[serde(rename = "members.create")]
    MemberCreate,
    #[serde(rename = "members.update")]
    MemberUpdate,
    #[serde(rename = "members.avatar.set")]
    MemberAvatar,
    #[serde(rename = "members.runtime.set")]
    MemberRuntime,
    #[serde(rename = "members.runtime.clear")]
    MemberClearRuntime,
    #[serde(rename = "workspaces.inspect")]
    WorkspaceInspect,
    #[serde(rename = "workspaces.validate")]
    WorkspaceValidate,
    #[serde(rename = "agentRunImages.read")]
    RunImages,
    #[serde(rename = "agentRunFileChanges.get")]
    RunFiles,
    #[serde(rename = "agentRuns.diagnostic.get")]
    RunDiagnostic,
    #[serde(rename = "runtime.product.ensure")]
    RuntimeEnsure,
    #[serde(rename = "runtime.product.check")]
    RuntimeCheck,
    #[serde(rename = "runtime.modelCatalog.open")]
    RuntimeCatalog,
    #[serde(rename = "runtime.discovery.rescan")]
    RuntimeDiscover,
}

impl Operation {
    pub fn timeout(self) -> std::time::Duration {
        std::time::Duration::from_secs(match self {
            Self::MissionCleanupRetry
            | Self::MissionChanges
            | Self::MissionFileDiff
            | Self::RuntimeCheck
            | Self::RuntimeCatalog
            | Self::RuntimeDiscover
            | Self::RuntimeStartupCheck
            | Self::RuntimeStartupInspect
            | Self::SkillGithubInspect => 120,
            _ => 15,
        })
    }
    pub fn project(self, mut value: serde_json::Value) -> serde_json::Value {
        use serde_json::json;
        match self {
            Self::AppInfo => json!({"name":value["name"],"version":value["version"]}),
            // Core owns credential redaction and digest-CAS. These projections
            // admit the fields used by the shared editor, never future fields.
            Self::Mcp | Self::McpRepair => project_mcp_config(value),
            Self::McpCreate
            | Self::McpUpdate
            | Self::McpMembers
            | Self::McpEnable
            | Self::McpDelete
            | Self::McpImport => {
                let mut projected = select_fields(
                    &value,
                    &[
                        "status",
                        "configDigest",
                        "actualConfigDigest",
                        "issues",
                        "serverId",
                    ],
                );
                if value.get("config").is_some() {
                    projected["config"] = project_mcp_config(value["config"].take());
                }
                projected
            }
            // This response is requested by the explicit reveal control. It is
            // never included in a list, event, automatic retry or receipt.
            Self::McpReveal => select_fields(
                &value,
                &[
                    "status",
                    "serverId",
                    "configDigest",
                    "actualConfigDigest",
                    "definitionJson",
                    "issues",
                ],
            ),
            // Preserve only individually admitted actions and the Core decision.
            // Unknown/future actions remain unavailable at the network boundary.
            _ => {
                filter_actions(
                    &mut value,
                    matches!(self, Self::Tasks | Self::Task | Self::CampOpen),
                );
                value
            }
        }
    }

    pub fn method(self) -> &'static str {
        match self {
            Self::NewConversationGet => "preferences.newConversation.get",
            Self::NewConversationSetDefaults => "preferences.newConversation.setDefaults",
            Self::NewConversationSetOneClick => "preferences.newConversation.setOneClick",
            Self::NewConversationInvalidate => "preferences.newConversation.invalidate",
            Self::MissionWorkspaceCleanup => "missions.workspace.cleanup",
            Self::MissionCleanupList => "missions.cleanup.list",
            Self::MissionCleanupRetry => "missions.cleanup.retry",
            Self::MissionList => "missions.list",
            Self::MissionGet => "missions.get",
            Self::MissionActivity => "missions.activity",
            Self::MissionDelivery => "missions.delivery",
            Self::MissionChanges => "missions.changes",
            Self::MissionFileDiff => "missions.fileDiff",
            Self::MissionDiffSessionRelease => "missions.diffSession.release",
            Self::MissionCreate => "missions.create",
            Self::MissionUpdate => "missions.update",
            Self::MissionStatus => "missions.status",
            Self::MissionStart => "missions.start",
            Self::MissionLinkPr => "missions.linkPr",
            Self::CampRename => "camps.rename",
            Self::CampDelete => "camps.delete",
            Self::CampDeletionIssues => "camps.deletionIssues",
            Self::CampRetryDeletion => "camps.retryDeletion",
            Self::CampDiscardPending => "camps.discardPending",
            Self::CampFastCheck => "camps.members.fast.check",
            Self::CampFastSet => "camps.members.fast.set",
            Self::MemberRemovalPreview => "members.removalPreview",
            Self::MemberRemove => "members.remove",
            Self::MemberReorder => "members.reorder",
            Self::SubsystemRetry => "runtime.subsystems.retry",
            Self::NotificationInbox => "notifications.inbox",
            Self::NotificationChanges => "notifications.changesSince",
            Self::NotificationPreference => "notifications.preference.get",
            Self::NotificationPreferenceUpdate => "notifications.preference.update",
            Self::NotificationAcknowledge => "notifications.acknowledge",
            Self::NotificationVisible => "notifications.acknowledgeVisibleSources",
            Self::DiagnosticsCheck => "diagnostics.check",
            Self::DiagnosticsExport => "diagnostics.export",
            Self::SkillReconcile => "skills.reconcile",

            Self::SkillContent => "skills.content.read",
            Self::SkillImportInspect => "skills.import.inspect",
            Self::SkillGithubInspect => "skills.import.github.inspect",
            Self::SkillImportCommit => "skills.import.commit",
            Self::SkillEnable => "skills.setEnabled",
            Self::SkillGroupsSet => "skills.setGroupAssignments",
            Self::SkillDelete => "skills.delete",
            Self::McpCreate => "mcp.servers.create",
            Self::McpUpdate => "mcp.servers.update",
            Self::McpMembers => "mcp.servers.setMembers",
            Self::McpEnable => "mcp.servers.setEnabled",
            Self::McpDelete => "mcp.servers.delete",
            Self::McpReveal => "mcp.servers.reveal",
            Self::McpRepair => "mcp.config.repairPermissions",
            Self::McpScan => "mcp.import.scan",
            Self::McpImport => "mcp.import.commit",
            Self::RuntimeStartupGet => "runtime.startup.get",
            Self::RuntimeStartupSave => "runtime.startup.save",
            Self::RuntimeStartupInspect => "runtime.startup.inspect",
            Self::RuntimeStartupCheck => "runtime.startup.check",

            Self::NavigationFindCamp => "navigation.findCamp",
            Self::RunExecutionPage => "agentRunExecution.page",
            Self::RunExecutionChanges => "agentRunExecution.changes",
            Self::TaskCreate => "tasks.create",
            Self::TaskUpdate => "tasks.update",
            Self::SingleChatList => "singleChat.list",
            Self::SingleChatGet => "singleChat.get",
            Self::SingleChatOpen => "singleChat.open",
            Self::SingleChatSend => "singleChat.send",
            Self::SingleChatEnd => "singleChat.end",
            Self::SingleChatPendingEdit => "singleChat.pendingInputs.edit",
            Self::SingleChatRemoveAttachment => "singleChat.composerDraft.removeAttachment",

            Self::MemoryCreate => "memory.create",
            Self::MemoryRevise => "memory.revise",
            Self::MemoryRetire => "memory.retire",
            Self::MemoryReactivate => "memory.reactivate",
            Self::MemoryForget => "memory.forget",
            Self::MemorySupersede => "memory.supersede",
            Self::MemorySchedule => "memory.review.schedule",
            Self::MemoryAccept => "memory.hearthReviewItems.accept",
            Self::MemoryReject => "memory.hearthReviewItems.reject",
            Self::MemoryExport => "memory.export",
            Self::AutomationCreate => "automations.create",
            Self::AutomationUpdate => "automations.update",
            Self::AutomationClose => "automations.close",
            Self::AutomationDelete => "automations.delete",
            Self::AutomationRun => "automations.run",

            Self::RuntimeEnsure => "runtime.product.ensure",
            Self::RuntimeCheck => "runtime.product.check",
            Self::RuntimeCatalog => "runtime.modelCatalog.open",
            Self::RuntimeDiscover => "runtime.discovery.rescan",
            Self::DraftQuote => "messageQuotes.mutateDraft",
            Self::CaptureQuote => "messageQuotes.capture",
            Self::Send => "camp.messages.send",
            Self::WithdrawMessage => "camp.messages.withdraw",
            Self::Approval => "action.approvals.resolve",
            Self::CancelRun => "agentRuns.cancel",
            Self::Reconcile => "commands.reconcile",
            Self::CampCreate => "camps.create",
            Self::CampCreationDefaults => "camps.creationPreflight",
            Self::CampAddMember => "camps.members.add",
            Self::CampRemoveMember => "camps.members.remove",
            Self::CampRemovalPreview => "camps.members.removalPreview",
            Self::CampLead => "camps.changeDefaultLead",
            Self::MemberCreate => "members.create",
            Self::MemberUpdate => "members.update",
            Self::MemberAvatar => "members.avatar.set",
            Self::MemberRuntime => "members.runtime.set",
            Self::MemberClearRuntime => "members.runtime.clear",
            Self::WorkspaceInspect => "workspaces.inspect",
            Self::WorkspaceValidate => "workspaces.validate",
            Self::RunImages => "agentRunImages.read",
            Self::RunFiles => "agentRunFileChanges.get",
            Self::RunDiagnostic => "agentRuns.diagnostic.get",
            Self::CampOpen => "camps.open",
            Self::CampEnter => "camps.enter",
            Self::CampViewed => "navigation.campViewed",
            Self::MemoryReviews => "memory.hearthReviewItems.list",
            Self::Health => "health.check",
            Self::SkillGroups => "skills.deliveryGroups.list",
            Self::RunEvidence => "agentRunEvidence.list",
            Self::RunEvidenceContent => "agentRunEvidence.getContent",
            Self::AppInfo => "app.info",
            Self::Members => "members.list",
            Self::Member => "members.get",
            Self::Navigation => "navigation.snapshot",
            Self::NavigationCamps => "navigation.camps",
            Self::GroupCamps => "navigation.groupCamps",
            Self::CampExists => "camps.exists",
            Self::Messages => "camp.messages.page",
            Self::MessagesAround => "camp.messages.around",
            Self::FindMessages => "camp.messages.find",
            Self::Tasks => "tasks.list",
            Self::Task => "tasks.get",
            Self::Memories => "memory.list",
            Self::Memory => "memory.get",
            Self::Automations => "automations.list",
            Self::Automation => "automations.get",
            Self::AutomationRuns => "automations.runs.list",
            Self::Installations => "runtime.installations.list",
            Self::Subsystems => "runtime.subsystems.get",
            Self::Monitoring => "monitoring.snapshot",
            Self::Skills => "skills.list",
            Self::Skill => "skills.get",
            Self::ToolboxList => "toolbox.list",
            Self::ToolboxRead => "toolbox.read",
            Self::ToolboxSetMembers => "toolbox.setMembers",
            Self::NativeSkillsList => "nativeSkills.list",
            Self::NativeSkillsRead => "nativeSkills.read",
            Self::SkillCandidates => "skills.candidates",
            Self::Mcp => "mcp.config.get",
        }
    }
}

fn select_fields(value: &serde_json::Value, fields: &[&str]) -> serde_json::Value {
    let mut object = serde_json::Map::new();
    for field in fields {
        if let Some(value) = value.get(field) {
            object.insert((*field).into(), value.clone());
        }
    }
    serde_json::Value::Object(object)
}
fn project_mcp_config(value: serde_json::Value) -> serde_json::Value {
    let mut projected = select_fields(
        &value,
        &[
            "path",
            "exists",
            "configDigest",
            "publicConfigJson",
            "fileIssue",
            "permissionIssue",
        ],
    );
    projected["servers"] = serde_json::json!(
        value["servers"]
            .as_array()
            .map(|servers| servers
                .iter()
                .map(|server| select_fields(
                    server,
                    &[
                        "serverId",
                        "name",
                        "transport",
                        "endpoint",
                        "enabled",
                        "assignedAgentIds",
                        "source",
                        "riskLevel",
                        "riskAcknowledged",
                        "definitionJson",
                        "configurationIssues"
                    ]
                ))
                .collect::<Vec<_>>())
            .unwrap_or_default()
    );
    projected
}

fn filter_actions(value: &mut serde_json::Value, task_updates: bool) {
    match value {
        serde_json::Value::Object(object) => {
            if object.contains_key("availableActions") {
                let actions = if task_updates
                    && object
                        .get("taskId")
                        .is_some_and(serde_json::Value::is_string)
                {
                    object["availableActions"]
                        .as_array()
                        .map(|actions| {
                            actions
                                .iter()
                                .filter(|action| action.as_str() == Some("update"))
                                .cloned()
                                .collect::<Vec<_>>()
                        })
                        .unwrap_or_default()
                } else {
                    Vec::new()
                };
                object.insert("availableActions".into(), serde_json::json!(actions));
            }
            for value in object.values_mut() {
                filter_actions(value, task_updates);
            }
        }
        serde_json::Value::Array(array) => {
            for value in array {
                filter_actions(value, task_updates);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::Operation;
    use serde_json::json;

    // Owns the network projection boundary, not Core's internal MCP model.
    #[test]
    fn public_projection_excludes_mcp_credentials_and_desktop_mutation_actions() {
        let projected = Operation::Mcp.project(json!({"servers":[{
            "serverId":"fixture", "name":"Example", "enabled":true,
            "transport":"http", "assignedAgentIds":[],
            "headers":{"Authorization":"fixture-secret"},
            "definitionJson":"{\"mcpServers\":{\"Example\":{\"url\":\"********\"}}}", "endpoint":"********",
            "futureCredentialField":"fixture-secret"
        }]}));
        assert_eq!(
            projected,
            json!({"servers":[{"serverId":"fixture", "name":"Example", "enabled":true,
            "transport":"http", "assignedAgentIds":[], "definitionJson":"{\"mcpServers\":{\"Example\":{\"url\":\"********\"}}}", "endpoint":"********"}]})
        );
        assert_eq!(
            Operation::Tasks
                .project(json!({"items":[{"taskId":"task_fixture", "body":"keep content", "availableActions":["update","edit"]}]})),
            json!({"items":[{"taskId":"task_fixture", "body":"keep content", "availableActions":["update"]}]})
        );
        assert!(serde_json::from_value::<Operation>(json!("host.web.rotate")).is_err());
        assert!(
            serde_json::from_value::<Operation>(json!("camp.message.send_user_draft")).is_err()
        );
        let withdraw = serde_json::from_value::<Operation>(json!("camp.messages.withdraw"))
            .expect("User message withdrawal should be admitted by the Web Host");
        assert_eq!(withdraw.method(), "camp.messages.withdraw");
    }
}
